### ISSUE TITLE
App seems to be hanging when generating password

### ISSUE THREAD

**Issue by oyvindh** [dono-app/dono-ios#74]
Is there a synchronous operation when generating the password?

**Comment by PanosSakkos** [comment]
There is one and for a key of 17 characters the computation was taking too long because of a [bug](https://github.com/krzyzanowskim/CryptoSwift/issues/347) in the crypto library.

The library was [replaced](https://github.com/dono-app/dono-pod/issues/9) with [IDZSwiftCommonCrypto](https://github.com/iosdevzone/IDZSwiftCommonCrypto) which is a Swift wrapper for Apple's CommonCrypto library and that resolved the issue (build 2.2.0 for the iOS app).

Thanks for the report!
